services:
  - type: web
    name: saurabh
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && python manage.py create_superuser && gunicorn django_portfolio.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: saurabh.onrender.com
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@saurabh.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: change-this-password-in-render
      - key: DATABASE_URL
        fromDatabase:
          name: saurabh-postgres
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.1"
databases:
  - name: saurabh-postgres
    databaseName: saurabh_portfolio
    region: singapore
    plan: free
