# Generated by Django 6.0.4 on 2026-04-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('freelance', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='FontAwesome icon class', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_range', models.CharField(help_text='e.g., 2021-2024', max_length=50)),
                ('degree_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_range', models.CharField(help_text='e.g., 2024-2025', max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hero_image', models.ImageField(upload_to='hero_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/')),
                ('code_link', models.URLField(blank=True, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='FontAwesome icon class (e.g., fa-solid fa-mobile-alt)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='FontAwesome icon class (e.g., fa-brands fa-twitter)', max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
