# Generated by Django 5.2.5 on 2026-04-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_category_project_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='city',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='website',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='address',
            field=models.CharField(default='Tunis', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='first_name',
            field=models.CharField(default='Steve', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='languages',
            field=models.CharField(default='French, English', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='last_name',
            field=models.CharField(default='Milner', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='nationality',
            field=models.CharField(default='Tunisian', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='phone',
            field=models.CharField(default='+21621184010', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='skype',
            field=models.CharField(default='steve.milner', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='age',
            field=models.IntegerField(default=27),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='email',
            field=models.EmailField(default='you@mail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='freelance',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='querymessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
