# Generated by Django 5.2.5 on 2026-04-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_aboutsection_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
