# Generated by Django 5.2.5 on 2026-04-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_education_institution_education_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('description', models.TextField(help_text='Short description for the blog list')),
                ('content', models.TextField(help_text='Full blog content (You can use HTML tags like <b>, <p>, <br> here)')),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
