# Generated by Django 5.2.5 on 2026-04-25 19:59

import portfolio.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='cv_file',
            field=models.FileField(blank=True, null=True, storage=portfolio.storage.HybridRawStorage(), upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=portfolio.storage.HybridImageStorage(), upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='hero_image',
            field=models.ImageField(storage=portfolio.storage.HybridImageStorage(), upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(storage=portfolio.storage.HybridImageStorage(), upload_to='projects/'),
        ),
    ]
